-- Create Database if not exists
IF NOT EXISTS (SELECT * FROM sys.databases WHERE name = N'fincrm')
BEGIN
  CREATE DATABASE fincrm;
END;
GO

USE fincrm;
GO

-- Company Master
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[MASCOM]') AND type in (N'U'))
BEGIN
  CREATE TABLE MASCOM (
    mascom_id NVARCHAR(50) PRIMARY KEY,
    company_name NVARCHAR(255) NOT NULL,
    industry_type NVARCHAR(255) NOT NULL,
    city NVARCHAR(255) NOT NULL,
    state NVARCHAR(255) NOT NULL,
    data_source NVARCHAR(255) NOT NULL,
    erp_using NVARCHAR(255),
    user_name NVARCHAR(255) NOT NULL,
    mascom_remarks NVARCHAR(MAX),
    ho NVARCHAR(255),
    plant NVARCHAR(255),
    web NVARCHAR(255),
    units NVARCHAR(50),
    users NVARCHAR(50),
    client NVARCHAR(50),
    follow NVARCHAR(50),
    want NVARCHAR(MAX),
    seen NVARCHAR(MAX),
    budget NVARCHAR(100),
    quoted NVARCHAR(100),
    turnover NVARCHAR(100),
    created_at DATETIME2 DEFAULT GETDATE(),
    updated_at DATETIME2 DEFAULT GETDATE()
  );
END;
GO

-- Migration commands for existing MASCOM table in MSSQL
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[MASCOM]') AND type in (N'U'))
BEGIN
  IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MASCOM' AND COLUMN_NAME = 'ho')
    ALTER TABLE MASCOM ADD ho NVARCHAR(255);
  IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MASCOM' AND COLUMN_NAME = 'plant')
    ALTER TABLE MASCOM ADD plant NVARCHAR(255);
  IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MASCOM' AND COLUMN_NAME = 'web')
    ALTER TABLE MASCOM ADD web NVARCHAR(255);
  IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MASCOM' AND COLUMN_NAME = 'units')
    ALTER TABLE MASCOM ADD units NVARCHAR(50);
  IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MASCOM' AND COLUMN_NAME = 'users')
    ALTER TABLE MASCOM ADD users NVARCHAR(50);
  IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MASCOM' AND COLUMN_NAME = 'client')
    ALTER TABLE MASCOM ADD client NVARCHAR(50);
  IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MASCOM' AND COLUMN_NAME = 'follow')
    ALTER TABLE MASCOM ADD follow NVARCHAR(50);
  IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MASCOM' AND COLUMN_NAME = 'want')
    ALTER TABLE MASCOM ADD want NVARCHAR(MAX);
  IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MASCOM' AND COLUMN_NAME = 'seen')
    ALTER TABLE MASCOM ADD seen NVARCHAR(MAX);
  IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MASCOM' AND COLUMN_NAME = 'budget')
    ALTER TABLE MASCOM ADD budget NVARCHAR(100);
  IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MASCOM' AND COLUMN_NAME = 'quoted')
    ALTER TABLE MASCOM ADD quoted NVARCHAR(100);
  IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MASCOM' AND COLUMN_NAME = 'turnover')
    ALTER TABLE MASCOM ADD turnover NVARCHAR(100);
  IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MASCOM' AND COLUMN_NAME = 'acts_json')
    ALTER TABLE MASCOM ADD acts_json NVARCHAR(MAX);
  IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MASCOM' AND COLUMN_NAME = 'contacts_json')
    ALTER TABLE MASCOM ADD contacts_json NVARCHAR(MAX);
  IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MASCOM' AND COLUMN_NAME = 'activity_data')
    ALTER TABLE MASCOM ADD activity_data NVARCHAR(MAX);
  IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MASCOM' AND COLUMN_NAME = 'remarks_data')
    ALTER TABLE MASCOM ADD remarks_data NVARCHAR(MAX);
END;
GO

-- Contact Master
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[MASCON]') AND type in (N'U'))
BEGIN
  CREATE TABLE MASCON (
    mascon_id NVARCHAR(50) PRIMARY KEY,
    mascom_id NVARCHAR(50) NOT NULL,
    contact_name NVARCHAR(255) NOT NULL,
    designation NVARCHAR(255),
    mobile NVARCHAR(100),
    email NVARCHAR(255),
    key_person NVARCHAR(255) DEFAULT 'N',
    user_name NVARCHAR(255) NOT NULL,
    mascon_remarks NVARCHAR(MAX),
    created_at DATETIME2 DEFAULT GETDATE(),
    updated_at DATETIME2 DEFAULT GETDATE(),
    CONSTRAINT fk_mascon_mascom FOREIGN KEY (mascom_id) REFERENCES MASCOM(mascom_id) ON DELETE CASCADE
  );
END;
GO

-- Transaction / Demo / Follow-up Master
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TRACOM]') AND type in (N'U'))
BEGIN
  CREATE TABLE TRACOM (
    tracom_id NVARCHAR(50) PRIMARY KEY,
    mascom_id NVARCHAR(50) NOT NULL,
    mascon_id NVARCHAR(50) NOT NULL,
    tracom_date DATE,
    demo_date DATE,
    demo_time TIME,
    demo_mode NVARCHAR(100),
    price_quoted DECIMAL(15, 2),
    amc_quoted DECIMAL(15, 2),
    mode NVARCHAR(100),
    user_name NVARCHAR(255) NOT NULL,
    remarks NVARCHAR(MAX),
    followup_date DATE,
    followup_time TIME,
    created_at DATETIME2 DEFAULT GETDATE(),
    updated_at DATETIME2 DEFAULT GETDATE(),
    CONSTRAINT fk_tracom_mascom FOREIGN KEY (mascom_id) REFERENCES MASCOM(mascom_id) ON DELETE CASCADE,
    CONSTRAINT fk_tracom_mascon FOREIGN KEY (mascon_id) REFERENCES MASCON(mascon_id)
  );
END;
GO

-- User Settings / Page Layout preferences
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[USER_SETTINGS]') AND type in (N'U'))
BEGIN
  CREATE TABLE USER_SETTINGS (
    page_name NVARCHAR(255) NOT NULL,
    user_key NVARCHAR(255) NOT NULL,
    setting_data NVARCHAR(MAX) NOT NULL,
    created_at DATETIME2 DEFAULT GETDATE(),
    updated_at DATETIME2 DEFAULT GETDATE(),
    PRIMARY KEY (page_name, user_key)
  );
END;
GO

-- Optimization Indexes
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = N'idx_mascom_name' AND object_id = OBJECT_ID(N'[dbo].[MASCOM]'))
  CREATE INDEX idx_mascom_name ON MASCOM(company_name);

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = N'idx_mascom_city' AND object_id = OBJECT_ID(N'[dbo].[MASCOM]'))
  CREATE INDEX idx_mascom_city ON MASCOM(city);

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = N'idx_mascom_state' AND object_id = OBJECT_ID(N'[dbo].[MASCOM]'))
  CREATE INDEX idx_mascom_state ON MASCOM(state);

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = N'idx_mascon_mascom' AND object_id = OBJECT_ID(N'[dbo].[MASCON]'))
  CREATE INDEX idx_mascon_mascom ON MASCON(mascom_id);

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = N'idx_tracom_mascom' AND object_id = OBJECT_ID(N'[dbo].[TRACOM]'))
  CREATE INDEX idx_tracom_mascom ON TRACOM(mascom_id);

-- Sub Master Configuration Lookup Tables
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[SUB_MASTERS]') AND type in (N'U'))
BEGIN
  CREATE TABLE SUB_MASTERS (
    id INT IDENTITY(1,1) PRIMARY KEY,
    master_type NVARCHAR(100) NOT NULL,
    value_name NVARCHAR(255) NOT NULL,
    created_at DATETIME2 DEFAULT GETDATE(),
    CONSTRAINT unique_type_value UNIQUE (master_type, value_name)
  );
END;
GO
