export const CHECKLIST_ITEMS = [
  { st: "Stage 1: Lead Generation", a: "Cold Calling", r: "Sales Person", p: true, e: "", m: false, t: "" },
  { st: "Stage 1: Lead Generation", a: "Cold Email", r: "Sales Person", p: true, e: "", m: false, t: "" },
  { st: "Stage 1: Lead Generation", a: "Bulk Mail Campaign", r: "Sales Person", p: true, e: "", m: false, t: "" },
  { st: "Stage 1: Lead Generation", a: "LinkedIn Contact", r: "Sales Person", p: true, e: "", m: false, t: "" },
  { st: "Stage 1: Lead Generation", a: "WhatsApp Introduction", r: "Sales Person", p: true, e: "", m: false, t: "" },
  { st: "Stage 1: Lead Generation", a: "Reference Received", r: "Sales Person", p: true, e: "", m: false, t: "" },
  { st: "Stage 1: Lead Generation", a: "Website Inquiry", r: "System", p: true, e: "", m: false, t: "" },
  { st: "Stage 1: Lead Generation", a: "Trade Fair / Exhibition Lead", r: "Sales Person", p: true, e: "", m: false, t: "" },
  { st: "Stage 1: Lead Generation", a: "Webinar Lead", r: "Sales Person", p: true, e: "", m: false, t: "" },
  { st: "Stage 1: Lead Generation", a: "Existing Customer Reference", r: "Sales Person", p: true, e: "", m: false, t: "" },

  { st: "Stage 2: Lead Qualification", a: "First Contact Call", r: "Sales Person", p: false, e: "Call log", m: true, t: "Within 24 hours of enquiry" },
  { st: "Stage 2: Lead Qualification", a: "Follow-up Call", r: "Sales Person", p: true, e: "", m: false, t: "" },
  { st: "Stage 2: Lead Qualification", a: "Requirement Collection Call", r: "Sales Person", p: true, e: "Requirement note", m: true, t: "" },
  { st: "Stage 2: Lead Qualification", a: "Qualification Meeting", r: "Sales Person", p: true, e: "", m: false, t: "" },
  { st: "Stage 2: Lead Qualification", a: "Decision Maker Identification", r: "Sales Person", p: false, e: "Key contact marked", m: true, t: "" },
  { st: "Stage 2: Lead Qualification", a: "Budget Discussion", r: "Sales Person", p: true, e: "", m: false, t: "" },
  { st: "Stage 2: Lead Qualification", a: "Existing Software Assessment", r: "Sales Person", p: false, e: "", m: true, t: "" },
  { st: "Stage 2: Lead Qualification", a: "Competitor Information Collection", r: "Sales Person", p: true, e: "", m: false, t: "" },

  { st: "Stage 3: Demonstration", a: "Demo Scheduled", r: "Sales Person", p: true, e: "", m: true, t: "" },
  { st: "Stage 3: Demonstration", a: "Demo Rescheduled", r: "Sales Person", p: true, e: "Reason", m: false, t: "" },
  { st: "Stage 3: Demonstration", a: "Presenter Name Declared In Demonstration Group", r: "Sales Person", p: true, e: "", m: true, t: "" },
  { st: "Stage 3: Demonstration", a: "Meeting Link And Proposal Sent To Official E-Mail Id", r: "Sales Person", p: true, e: "E-mail", m: true, t: "" },
  { st: "Stage 3: Demonstration", a: "Virtual Demo", r: "Sales Person", p: true, e: "Signed attendance", m: true, t: "" },
  { st: "Stage 3: Demonstration", a: "Physical Demo", r: "Sales Person", p: true, e: "Signed attendance", m: true, t: "" },
  { st: "Stage 3: Demonstration", a: "Technical Demo", r: "Demonstration Team", p: true, e: "Signed attendance", m: false, t: "" },
  { st: "Stage 3: Demonstration", a: "Functional Demo", r: "Demonstration Team", p: true, e: "Signed attendance", m: false, t: "" },
  { st: "Stage 3: Demonstration", a: "Management Demo", r: "Demonstration Team", p: true, e: "Signed attendance", m: false, t: "" },
  { st: "Stage 3: Demonstration", a: "Re-Demo", r: "Demonstration Team", p: true, e: "Signed attendance", m: false, t: "" },
  { st: "Stage 3: Demonstration", a: "Department-wise Demo", r: "Demonstration Team", p: true, e: "Signed attendance", m: false, t: "" },
  { st: "Stage 3: Demonstration", a: "Demo Recording Shared", r: "Sales Person", p: true, e: "", m: false, t: "" },
  { st: "Stage 3: Demonstration", a: "Signed Demonstration Document Shared With Reporting Authority", r: "Sales Person", p: true, e: "Signed document", m: true, t: "" },
  { st: "Stage 3: Demonstration", a: "Demonstration Summary Shared With Client", r: "Sales Person", p: true, e: "E-mail", m: true, t: "Within 24 to 48 hours" },
  { st: "Stage 3: Demonstration", a: "Client Feedback Form Filled During The Session", r: "Sales Person", p: true, e: "Feedback form", m: true, t: "" },

  { st: "Stage 4: Requirement Analysis", a: "Requirement Collection", r: "Sales Person", p: true, e: "Requirement document", m: true, t: "" },
  { st: "Stage 4: Requirement Analysis", a: "Gap Analysis", r: "Demonstration Team", p: false, e: "Gap note", m: true, t: "" },
  { st: "Stage 4: Requirement Analysis", a: "Existing Process Study", r: "Demonstration Team", p: false, e: "", m: false, t: "" },
  { st: "Stage 4: Requirement Analysis", a: "Requirement Document Submission", r: "Sales Person", p: false, e: "Signed document", m: true, t: "" },
  { st: "Stage 4: Requirement Analysis", a: "Requirement Clarification", r: "Sales Person", p: true, e: "", m: false, t: "" },
  { st: "Stage 4: Requirement Analysis", a: "Customization Discussion", r: "Demonstration Team", p: true, e: "", m: false, t: "" },
  { st: "Stage 4: Requirement Analysis", a: "Workflow Design Discussion", r: "Demonstration Team", p: true, e: "", m: false, t: "" },
  { st: "Stage 4: Requirement Analysis", a: "Integration Discussion", r: "Demonstration Team", p: true, e: "", m: false, t: "" },

  { st: "Stage 5: Commercial Activity", a: "Budget Discussion", r: "Sales Person", p: true, e: "", m: false, t: "" },
  { st: "Stage 5: Commercial Activity", a: "Initial Commercial Shared Verbally Or On WhatsApp", r: "Sales Person", p: true, e: "", m: true, t: "" },
  { st: "Stage 5: Commercial Activity", a: "Commercial Proposal Sent", r: "Sales Person", p: true, e: "Proposal", m: true, t: "" },
  { st: "Stage 5: Commercial Activity", a: "Revised Proposal Sent", r: "Sales Person", p: true, e: "Proposal", m: false, t: "" },
  { st: "Stage 5: Commercial Activity", a: "Negotiation Meeting", r: "Sales Person", p: true, e: "", m: false, t: "" },
  { st: "Stage 5: Commercial Activity", a: "Discount Approval", r: "Reporting Authority", p: true, e: "Approval record", m: true, t: "" },
  { st: "Stage 5: Commercial Activity", a: "Commercial Clarification", r: "Sales Person", p: true, e: "", m: false, t: "" },
  { st: "Stage 5: Commercial Activity", a: "ROI Discussion", r: "Sales Person", p: true, e: "", m: false, t: "" },
  { st: "Stage 5: Commercial Activity", a: "Competitor Comparison", r: "Sales Person", p: true, e: "", m: false, t: "" },
  { st: "Stage 5: Commercial Activity", a: "First Commercial Discussion On Standard Printed Format", r: "Sales Person", p: true, e: "Standard format", m: true, t: "" },
  { st: "Stage 5: Commercial Activity", a: "Second Commercial Discussion On The Same Format", r: "Sales Person", p: true, e: "Standard format", m: false, t: "" },
  { st: "Stage 5: Commercial Activity", a: "Final Negotiation With Technical Head", r: "Sales Person", p: true, e: "", m: false, t: "" },
  { st: "Stage 5: Commercial Activity", a: "Agreement On Commercial Terms Signed On Printed Document", r: "Sales Person", p: false, e: "Signed document", m: true, t: "" },
  { st: "Stage 5: Commercial Activity", a: "Signed Commercial Submitted To Accounts", r: "Sales Person", p: false, e: "Signed document", m: true, t: "" },
  { st: "Stage 5: Commercial Activity", a: "Final Proposal Prepared By Accounts", r: "Accounts Department", p: false, e: "Proposal", m: true, t: "" },
  { st: "Stage 5: Commercial Activity", a: "Final Approval By Client Signature On Proposal", r: "Sales Person", p: false, e: "Signed proposal", m: true, t: "" },

  { st: "Stage 6: Order Finalization", a: "Purchase Intent Received", r: "Sales Person", p: false, e: "", m: false, t: "" },
  { st: "Stage 6: Order Finalization", a: "PO And Advance Requested From Client", r: "Sales Person", p: false, e: "", m: true, t: "" },
  { st: "Stage 6: Order Finalization", a: "Proforma Invoice Raised", r: "Accounts Department", p: false, e: "PI", m: true, t: "" },
  { st: "Stage 6: Order Finalization", a: "Purchase Order Received", r: "Sales Person", p: false, e: "PO", m: true, t: "Within 15 days of PI" },
  { st: "Stage 6: Order Finalization", a: "Advance Payment Received", r: "Accounts Department", p: false, e: "Receipt", m: true, t: "" },
  { st: "Stage 6: Order Finalization", a: "Agreement Sent", r: "Accounts Department", p: false, e: "Agreement", m: true, t: "" },
  { st: "Stage 6: Order Finalization", a: "Agreement Signed", r: "Sales Person", p: false, e: "Signed agreement", m: true, t: "" },
  { st: "Stage 6: Order Finalization", a: "Project Kickoff Approved", r: "Reporting Authority", p: false, e: "", m: true, t: "" },
  { st: "Stage 6: Order Finalization", a: "Handover To Implementation Team", r: "Implementation Team", p: false, e: "Handover note", m: true, t: "" },

  { st: "Stage 7: Implementation", a: "Project Kickoff Meeting", r: "Implementation Team", p: false, e: "Minutes of meeting", m: true, t: "" },
  { st: "Stage 7: Implementation", a: "Master Data Collection", r: "Implementation Team", p: false, e: "", m: true, t: "" },
  { st: "Stage 7: Implementation", a: "Data Migration", r: "Implementation Team", p: true, e: "Client sign-off", m: true, t: "" },
  { st: "Stage 7: Implementation", a: "Configuration Setup", r: "Implementation Team", p: true, e: "", m: true, t: "" },
  { st: "Stage 7: Implementation", a: "User Creation", r: "Implementation Team", p: true, e: "", m: true, t: "" },
  { st: "Stage 7: Implementation", a: "Department-wise Training", r: "Implementation Team", p: true, e: "Attendance sheet", m: true, t: "" },
  { st: "Stage 7: Implementation", a: "Opening Balances Entered And Tallied", r: "Implementation Team", p: false, e: "Tally statement", m: true, t: "" },
  { st: "Stage 7: Implementation", a: "Document Formats Configured — Invoice, BMR, BPR", r: "Implementation Team", p: true, e: "", m: true, t: "" },
  { st: "Stage 7: Implementation", a: "Parallel Run Started And Issues Closed", r: "Implementation Team", p: false, e: "Issue log", m: true, t: "" },
  { st: "Stage 7: Implementation", a: "UAT (User Acceptance Testing)", r: "Implementation Team", p: true, e: "UAT sign-off", m: true, t: "" },
  { st: "Stage 7: Implementation", a: "Go-Live Planning", r: "Implementation Team", p: false, e: "Plan", m: true, t: "" },
  { st: "Stage 7: Implementation", a: "Go-Live Approval", r: "Reporting Authority", p: false, e: "Approval", m: true, t: "" },
  { st: "Stage 7: Implementation", a: "Go-Live Completed", r: "Implementation Team", p: false, e: "Go-live certificate", m: true, t: "" },
  { st: "Stage 7: Implementation", a: "Balance Payment Collected On Go-Live", r: "Accounts Department", p: false, e: "Receipt", m: true, t: "" },
  { st: "Stage 7: Implementation", a: "Thirty Day Post Go-Live Review", r: "Implementation Team", p: false, e: "Minutes of meeting", m: true, t: "30 days after go-live" },
  { st: "Stage 7: Implementation", a: "Project Closure Certificate Signed By Client", r: "Implementation Team", p: false, e: "Closure certificate", m: true, t: "" },
  { st: "Stage 7: Implementation", a: "Account Handed Over From Implementation To Support", r: "Support Team", p: false, e: "Handover note", m: true, t: "" },

  { st: "Stage 8: Support", a: "Support Call", r: "Support Team", p: true, e: "", m: false, t: "" },
  { st: "Stage 8: Support", a: "Support Ticket", r: "Support Team", p: true, e: "Ticket", m: false, t: "" },
  { st: "Stage 8: Support", a: "Bug Report", r: "Support Team", p: true, e: "Ticket", m: false, t: "" },
  { st: "Stage 8: Support", a: "Bug Resolution", r: "Development Team", p: true, e: "Ticket", m: false, t: "" },
  { st: "Stage 8: Support", a: "Remote Support Session", r: "Support Team", p: true, e: "", m: false, t: "" },
  { st: "Stage 8: Support", a: "On-site Support Visit", r: "Support Team", p: true, e: "Visit report", m: false, t: "" },
  { st: "Stage 8: Support", a: "Escalation", r: "Reporting Authority", p: true, e: "", m: false, t: "" },
  { st: "Stage 8: Support", a: "Performance Review", r: "Support Team", p: true, e: "Review note", m: false, t: "" },

  { st: "Stage 9: Customization", a: "New Requirement Received", r: "Sales Person", p: true, e: "", m: false, t: "" },
  { st: "Stage 9: Customization", a: "Change Request", r: "Sales Person", p: true, e: "Change request", m: true, t: "" },
  { st: "Stage 9: Customization", a: "Customization Proposal", r: "Accounts Department", p: true, e: "Proposal", m: true, t: "" },
  { st: "Stage 9: Customization", a: "Customization Approval", r: "Reporting Authority", p: true, e: "Approval", m: true, t: "" },
  { st: "Stage 9: Customization", a: "Development Started", r: "Development Team", p: true, e: "", m: false, t: "" },
  { st: "Stage 9: Customization", a: "Testing", r: "Development Team", p: true, e: "Test record", m: true, t: "" },
  { st: "Stage 9: Customization", a: "Delivery", r: "Development Team", p: true, e: "", m: true, t: "" },
  { st: "Stage 9: Customization", a: "User Sign-off", r: "Implementation Team", p: true, e: "Signed sign-off", m: true, t: "" },

  { st: "Stage 10: AMC", a: "AMC Reminder", r: "Accounts Department", p: true, e: "", m: true, t: "60, 30 and 15 days before expiry" },
  { st: "Stage 10: AMC", a: "AMC Proposal", r: "Accounts Department", p: true, e: "Proposal", m: true, t: "" },
  { st: "Stage 10: AMC", a: "AMC Negotiation", r: "Sales Person", p: true, e: "", m: false, t: "" },
  { st: "Stage 10: AMC", a: "AMC Renewal", r: "Accounts Department", p: true, e: "AMC invoice", m: true, t: "" },
  { st: "Stage 10: AMC", a: "AMC Expired", r: "System", p: true, e: "", m: true, t: "" },
  { st: "Stage 10: AMC", a: "AMC Reactivated", r: "Accounts Department", p: true, e: "", m: false, t: "" },

  { st: "Stage 11: Upgrades", a: "New Version Announcement", r: "Support Team", p: true, e: "", m: false, t: "" },
  { st: "Stage 11: Upgrades", a: "Upgrade Discussion", r: "Support Team", p: true, e: "", m: false, t: "" },
  { st: "Stage 11: Upgrades", a: "Upgrade Proposal", r: "Accounts Department", p: true, e: "Proposal", m: false, t: "" },
  { st: "Stage 11: Upgrades", a: "Upgrade Installation", r: "Implementation Team", p: true, e: "", m: true, t: "" },
  { st: "Stage 11: Upgrades", a: "Upgrade Training", r: "Implementation Team", p: true, e: "Attendance sheet", m: true, t: "" },

  { st: "Stage 12: Additional Revenue", a: "Additional User License", r: "Sales Person", p: true, e: "PO", m: false, t: "" },
  { st: "Stage 12: Additional Revenue", a: "Additional Module Sale", r: "Sales Person", p: true, e: "PO", m: false, t: "" },
  { st: "Stage 12: Additional Revenue", a: "New Plant Implementation", r: "Sales Person", p: true, e: "PO", m: false, t: "" },
  { st: "Stage 12: Additional Revenue", a: "Multi-Location Expansion", r: "Sales Person", p: true, e: "PO", m: false, t: "" },
  { st: "Stage 12: Additional Revenue", a: "Mobile App Sale", r: "Sales Person", p: true, e: "PO", m: false, t: "" },
  { st: "Stage 12: Additional Revenue", a: "BI Dashboard Sale", r: "Sales Person", p: true, e: "PO", m: false, t: "" },
  { st: "Stage 12: Additional Revenue", a: "New Integration Sale", r: "Sales Person", p: true, e: "PO", m: false, t: "" },

  { st: "Stage 13: Relationship Management", a: "Customer Visit", r: "Sales Person", p: true, e: "Visit report", m: false, t: "" },
  { st: "Stage 13: Relationship Management", a: "Festival Greeting", r: "Sales Person", p: true, e: "", m: false, t: "" },
  { st: "Stage 13: Relationship Management", a: "Customer Feedback", r: "Support Team", p: true, e: "Feedback form", m: false, t: "" },
  { st: "Stage 13: Relationship Management", a: "Satisfaction Survey", r: "Support Team", p: true, e: "Survey", m: false, t: "" },
  { st: "Stage 13: Relationship Management", a: "Reference Request", r: "Sales Person", p: true, e: "", m: false, t: "" },
  { st: "Stage 13: Relationship Management", a: "Success Story / Case Study", r: "Sales Person", p: true, e: "Case study", m: false, t: "" },

  { st: "Stage 14: Closure / Exit", a: "Customer Lost", r: "Sales Person", p: false, e: "Reason recorded", m: true, t: "" },
  { st: "Stage 14: Closure / Exit", a: "Competitor Replaced", r: "Sales Person", p: false, e: "Competitor name", m: true, t: "" },
  { st: "Stage 14: Closure / Exit", a: "Project Suspended", r: "Reporting Authority", p: false, e: "Reason recorded", m: true, t: "" },
  { st: "Stage 14: Closure / Exit", a: "Blacklisted", r: "Reporting Authority", p: false, e: "Approval", m: true, t: "" },
  { st: "Stage 14: Closure / Exit", a: "Customer Reactivated", r: "Sales Person", p: true, e: "", m: false, t: "" }
];

export const CHECKLIST_STAGES = [...new Set(CHECKLIST_ITEMS.map(item => item.st))];
