export const SEARCH_COLUMNS = [
  // MASCOM
  { k: 'code',        lab: 'Code',                  table: 'MASCOM', cls: 'mono', get: r => r.co.mascom_id },
  { k: 'name',        lab: 'Company Name',          table: 'MASCOM', cls: 'co', def: true, get: r => r.co.company_name },
  { k: 'ind',         lab: 'Industry Type',         table: 'MASCOM', cls: 'muted', def: true, get: r => r.co.industry_type },
  { k: 'city',        lab: 'City',                  table: 'MASCOM', cls: 'muted', def: true, get: r => r.co.city },
  { k: 'state',       lab: 'State',                 table: 'MASCOM', cls: 'muted', get: r => r.co.state },
  { k: 'ho',          lab: 'Head Office',           table: 'MASCOM', cls: 'muted', get: r => r.co.ho },
  { k: 'plant',       lab: 'Plant Location',        table: 'MASCOM', cls: 'muted', get: r => r.co.plant },
  { k: 'web',         lab: 'Website',               table: 'MASCOM', cls: 'muted', get: r => r.co.web },
  { k: 'erp',         lab: 'Present ERP',           table: 'MASCOM', cls: 'muted', get: r => r.co.erp_using },
  { k: 'users',       lab: 'No. Of Users',          table: 'MASCOM', cls: 'mono r', get: r => r.co.users },
  { k: 'units',       lab: 'No. Of Units',          table: 'MASCOM', cls: 'mono r', get: r => r.co.units },
  { k: 'src',         lab: 'Data Source',           table: 'MASCOM', cls: 'muted', get: r => r.co.data_source },
  { k: 'owner',       lab: 'Owner',                 table: 'MASCOM', cls: 'muted', get: r => r.co.user_name },
  { k: 'logged',      lab: 'Logged By',             table: 'MASCOM', cls: 'muted', get: r => r.co.user_name },
  { k: 'follow',      lab: 'Next Follow-Up Date',   table: 'MASCOM', cls: 'mono', get: r => r.co.follow },
  { k: 'products',    lab: 'Product Type',          table: 'MASCOM', cls: 'muted', get: r => r.co.products || '—' },
  { k: 'legal',       lab: 'Legal Name',            table: 'MASCOM', cls: 'muted', get: r => r.co.legal || '—' },
  { k: 'entity',      lab: 'Entity Type',           table: 'MASCOM', cls: 'muted', get: r => r.co.entity || '—' },
  { k: 'biztype',     lab: 'Business Type',         table: 'MASCOM', cls: 'muted', get: r => r.co.biztype || '—' },
  { k: 'subind',      lab: 'Sub-Industry',          table: 'MASCOM', cls: 'muted', get: r => r.co.subind || '—' },
  { k: 'status',      lab: 'Company Status',        table: 'MASCOM', cls: 'muted', get: r => r.co.status || 'Active' },
  { k: 'mainph',      lab: 'Main Phone',            table: 'MASCOM', cls: 'mono', get: r => r.key.mobile || '—' },
  { k: 'mainmail',    lab: 'Main E-Mail',           table: 'MASCOM', cls: 'muted', get: r => r.key.email || '—' },
  { k: 'emp',         lab: 'Employee Count',        table: 'MASCOM', cls: 'mono r', get: r => r.co.emp || '—' },
  { k: 'turnover',    lab: 'Annual Turnover',       table: 'MASCOM', cls: 'muted', get: r => r.co.turnover },
  { k: 'prospect',    lab: 'FINAMAN Prospect',      table: 'MASCOM', cls: 'muted', get: r => r.co.prospect || 'Yes' },
  { k: 'priority',    lab: 'Prospect Priority',     table: 'MASCOM', cls: 'muted', get: r => r.co.priority || 'High' },
  { k: 'pan',         lab: 'PAN',                   table: 'MASCOM', cls: 'mono', get: r => r.co.pan || '—' },
  { k: 'gstin',       lab: 'GSTIN',                 table: 'MASCOM', cls: 'mono', get: r => r.co.gstin || '—' },
  { k: 'cert',        lab: 'Certification Type',    table: 'MASCOM', cls: 'muted', get: r => r.co.cert || '—' },
  { k: 'district',    lab: 'District',              table: 'MASCOM', cls: 'muted', get: r => r.co.district || r.co.city },
  { k: 'pin',         lab: 'Postal Code',           table: 'MASCOM', cls: 'mono', get: r => r.co.pin || '—' },
  { k: 'leadid',      lab: 'Lead ID',               table: 'MASCOM', cls: 'mono', get: r => r.co.leadid || '—' },
  { k: 'leadstatus',  lab: 'Lead Status',           table: 'MASCOM', cls: 'muted', get: r => r.co.leadstatus || 'Warm' },
  { k: 'potential',   lab: 'FINAMAN Potential',     table: 'MASCOM', cls: 'muted', get: r => r.co.potential || 'High' },
  { k: 'score',       lab: 'Lead Score',            table: 'MASCOM', cls: 'mono r', get: r => r.co.score || '85' },
  { k: 'erpreq',      lab: 'ERP Requirement',       table: 'MASCOM', cls: 'muted', get: r => r.co.erpreq || 'Full ERP' },
  { k: 'decmaker',    lab: 'Decision Maker',        table: 'MASCOM', cls: 'muted', get: r => r.co.decmaker || r.key.contact_name },
  { k: 'dealvalue',   lab: 'Estimated Deal Value',  table: 'MASCOM', cls: 'mono r', get: r => r.co.dealvalue || '—' },
  { k: 'client',      lab: 'Client',                table: 'MASCOM', cls: 'muted', get: r => r.co.client },
  { k: 'budget',      lab: 'Budget',                table: 'MASCOM', cls: 'muted', get: r => r.co.budget },
  { k: 'seen',        lab: 'Competitors Seen',      table: 'MASCOM', cls: 'muted', get: r => r.co.seen },
  { k: 'want',        lab: 'Requirement',           table: 'MASCOM', cls: 'muted', get: r => r.co.want },
  { k: 'rem',         lab: 'Company Remarks',       table: 'MASCOM', cls: 'muted', get: r => r.co.mascom_remarks },

  // MASCON
  { k: 'ccode',       lab: 'Contact Code',          table: 'MASCON', cls: 'mono', get: r => r.key.mascon_id || '—' },
  { k: 'person',      lab: 'Contact Person',        table: 'MASCON', cls: '', def: true, get: r => r.key.contact_name || '—' },
  { k: 'desig',       lab: 'Designation',           table: 'MASCON', cls: 'muted', get: r => r.key.designation || '—' },
  { k: 'mobile',      lab: 'Mobile No',             table: 'MASCON', cls: 'mono', def: true, get: r => r.key.mobile || '—' },
  { k: 'alt',         lab: 'Alternate Mobile',      table: 'MASCON', cls: 'mono', get: r => r.key.alt || '—' },
  { k: 'email',       lab: 'E-Mail',                table: 'MASCON', cls: 'muted', get: r => r.key.email || '—' },
  { k: 'dept',        lab: 'Department',            table: 'MASCON', cls: 'muted', get: r => r.key.dept || 'Management' },
  { k: 'ncontacts',   lab: 'No. Of Contacts',       table: 'MASCON', cls: 'mono r', get: r => r.contacts.length },
  { k: 'din',         lab: 'DIN',                   table: 'MASCON', cls: 'mono', get: r => r.key.din || '—' },
  { k: 'linkedin',    lab: 'LinkedIn',              table: 'MASCON', cls: 'muted', get: r => r.key.linkedin || '—' },
  { k: 'cdecision',   lab: 'Decision Maker',        table: 'MASCON', cls: 'muted', get: r => r.key.cdecision || 'Yes' },

  // TRACOM
  { k: 'first',       lab: 'First Contact',         table: 'TRACOM', cls: 'mono', def: true, get: r => r.lastAct ? r.lastAct.tracom_date : '—' },
  { k: 'demo',        lab: 'Demo Date',             table: 'TRACOM', cls: 'mono', def: true, get: r => r.lastDemo ? r.lastDemo.demo_date : '—' },
  { k: 'visit',       lab: 'Visit Date',            table: 'TRACOM', cls: 'mono', get: r => r.visitDate || '—' },
  { k: 'last',        lab: 'Last Activity',         table: 'TRACOM', cls: 'mono', def: true, get: r => r.lastAct ? r.lastAct.tracom_date : '—' },
  { k: 'lasttype',    lab: 'Last Activity Type',    table: 'TRACOM', cls: 'muted', get: r => r.lastAct ? r.lastAct.mode : '—' },
  { k: 'lastby',      lab: 'Last Activity By',      table: 'TRACOM', cls: 'muted', get: r => r.lastAct ? r.lastAct.user_name : '—' },
  { k: 'lastrem',     lab: 'Last Remark',           table: 'TRACOM', cls: 'muted', get: r => r.lastAct ? r.lastAct.remarks : '—' },
  { k: 'nacts',       lab: 'Activities',            table: 'TRACOM', cls: 'mono r', get: r => r.acts.length },
  { k: 'ndemos',      lab: 'Demos',                 table: 'TRACOM', cls: 'mono r', get: r => r.acts.filter(a => a.mode === 'Demo').length },
  { k: 'quoted',      lab: 'Quoted Value',          table: 'TRACOM', cls: 'mono r', get: r => r.co.quoted || r.co.quoted_value || (r.lastQuote ? r.lastQuote.price_quoted : '—') },
  { k: 'amc',         lab: 'AMC',                   table: 'TRACOM', cls: 'mono r', get: r => r.lastQuote ? r.lastQuote.amc_quoted : '—' }
];

export const DEFAULT_VISIBLE_KEYS = SEARCH_COLUMNS.filter(c => c.def).map(c => c.k);
